[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "discord-leveling-bot"

[services.variables]
NODE_ENV = "production"

[[services]]
name = "postgresql"
type = "database"
