# railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100

[environments.production]
variables = { NODE_ENV = "production" }

[[services]]
name = "discord-leveling-bot"

[services.variables]
NODE_ENV = "production"
# Add your environment variables here or in Railway dashboard
